### ISSUE TITLE
The issue I have with you. Is that why did you try to leak IP of a person

### ISSUE THREAD

**Issue by SuperLexer9** [Realhack1/Issues#1]
That's illegal to do

**Comment by SuperLexer9** [comment]
Yep you know about McProgrammerX. He told me you said you will leak his IP and he said you are a hacker

**Comment by Realhack1** [comment]
you just made a acounnt

**Comment by Realhack1** [comment]
he called me a fake hacker

**Comment by Realhack1** [comment]
@SuperLexer9 you are Mcprogrammerx

**Comment by SuperLexer9** [comment]
<h1 onclick='alert('This kid sucks')'>CLICK THIS</h1>
<h1>It says YOU SUCK</h1>

<h1>It says YOU SUCK</h1>
<h1>It says YOU SUCK</h1>
<h1>It says YOU SUCK</h1>
<h1>It says YOU SUCK</h1>
<h1>It says YOU SUCK</h1>
<h1>It says YOU SUCK</h1>
<h1>It says YOU SUCK</h1>
